### ISSUE TITLE
Change <title> for deprecation page

### ISSUE THREAD

**Issue by jbuck** [mozilla/mofo-deprecation#4]
Right now it's "MoFo Deprecation Notice". Which is true! But it seems a little stiff. Any suggestions @secretrobotron @kevzawacki @hpauljohnson?

**Comment by secretrobotron** [comment]
Something like "Mozilla Foundation — Changes to Products and Services"?

**Comment by KevZawacki** [comment]
+1

**Comment by ashleygwilliams** [comment]
solved in be15eae3acdf7a6c384c80c6f338b2f2d35f6257
