### ISSUE TITLE
Change link to Webmaker projects

### ISSUE THREAD

**Issue by jbuck** [mozilla/mofo-deprecation#5]
Right now we're currently linking to the old Webmaker projects at https://webmaker.org/explore . Is there a projects page that works in the browser for Webmaker Android projects? Any suggestions @secretrobotron @kevzawacki @hpauljohnson?

**Comment by secretrobotron** [comment]
cc @xmatthewx

**Comment by xmatthewx** [comment]
In the app, the space to view projects by others is called Discover. We don't currently have anything built for viewing via browser. If and when we do, /discover would work if it doesn't live on the homepage itself. Are you wondering where to redirect URLs? It'll have to be the homepage for now. 

Related: We'll need to redirect Project URLs on relaunch from beta to wm.org. Their root shouldn't be used for a new explore or discover: https://beta.webmaker.org/#/project

Helpful info?

**Comment by jbuck** [comment]
@xmatthewx Ah dang. Okay, I think we should remove the link to https://webmaker.org/explore since that page only lists the deprecated content tools and not the new Webmaker projects.

**Comment by ashleygwilliams** [comment]
solved in 4a694c5d7d25ea88a8db72cb1f31cf63af71e688
