### ISSUE TITLE
Explain what deprecate means

### ISSUE THREAD

**Issue by edrushka** [mozilla/mofo-deprecation#8]
The deprecation page copy on https://popcorn.webmaker.org/ isn't very friendly for young people or non-native English speakers. Deprecate, as it's used here, isn't clear. Maybe try "retired" "shut down" "closed" or "cancelled".

cc @kevzawacki

**Comment by KevZawacki** [comment]
@edrushka Good point! I like "retired."

**Comment by cadecairos** [comment]
@KevZawacki @edrushka Is this a copy change we want on all deprecation pages or just on popcorn maker?

**Comment by edrushka** [comment]
Ideally on all the pages.
